- name: Ensure passage user exists
  ansible.builtin.user:
    name: "{{ passage_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Create config directory
  ansible.builtin.file:
    path: "{{ passage_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download passage binary
  ansible.builtin.get_url:
    url: "https://github.com/head-gardener/passage/releases/download/v{{ passage_version }}/passage-{{ ansible_architecture }}-v{{ passage_version }}"
    dest: "{{ passage_install_path }}"
    mode: '0755'
    owner: root
    group: root
  notify: restart passage

- name: Generate YAML config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ passage_config_path }}"
    mode: '0644'
    owner: root
    group: root
  notify: restart passage

- name: Install systemd unit
  ansible.builtin.template:
    src: passage.service.j2
    dest: /etc/systemd/system/passage.service
    mode: '0644'
  notify:
    - daemon-reload
    - restart passage

- name: Enable and start passage
  ansible.builtin.systemd:
    name: passage
    enabled: true
    state: started
