name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Build with Nix Flake
        run: |
          nix develop .#ci -c just binaries

      - name: Check binary
        run: |
          ./bin/passage-x86_64-${{ github.ref_name }} --help

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
